# Generated by Django 4.2.1 on 2023-05-22 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattachment',
            name='user',
        ),
        migrations.AddField(
            model_name='productattachment',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
